### ISSUE TITLE
vs code preview html API is being deprecated

### ISSUE THREAD

**Issue by lesterlxy** [Ciantic/keymapceditor-vsc#1]
The following notification appears when using the extension. 

`Extension 'Ciantic.keymapceditor-vsc' uses the 'vscode.previewHtml' command which is deprecated and will be removed soon. Please file an issue against this extension to update to use VS Code's webview API.`

**Comment by Ciantic** [comment]
Oh dear, does it work? I have to look at this.

**Comment by lesterlxy** [comment]
It runs but seems to be unable to load the keys. Not sure if it's related to the deprecation.

![Screenshot (21)](https://user-images.githubusercontent.com/795422/54071744-21c6de00-42ac-11e9-9514-e80322182528.png)

**Comment by Ciantic** [comment]
I upgraded it to use latest API, new version is 0.7.4.

And it seems to work now with the keymap you tried.

Thanks for reporting.
