### ISSUE TITLE
keymapCEditor shows up empty

### ISSUE THREAD

**Issue by cvillagrasa** [Ciantic/keymapceditor-vsc#5]
Hi, I'm using VSCode 1.58.2 on Ubuntu, and I'm having some trouble to use keymapCEditor:

![image](https://user-images.githubusercontent.com/57069798/126041348-762a0268-6059-4be1-a78e-8c2e485d38d8.png)

Anyone knows what may be happening? Thanks in advance,

**Comment by Ciantic** [comment]
I can confirm, something is broken! I will look into this.

**Comment by Ciantic** [comment]
It's now fixed. https://github.com/Ciantic/keymapceditor-vsc/commit/704a0aa6cc66fa843e6b63c12709164bf722e7bf

Update to 0.7.7 and it should work.

Thanks for  reporting!
